Configure JGit credentials provider with token
Without this, the sandbox update would fail with:

```
java.io.IOException: org.eclipse.jgit.api.errors.TransportException: https://***@github.com/neo4j-graph-examples/twitter.git: Authentication is required but no CredentialsProvider has been registered
```